### ISSUE TITLE
Nodes to Triggers

### ISSUE THREAD

**Issue by Altenhh** [gd-edit/GDE#139]
For each block groups (group ID or linked?) you will be able to create Nodes on where you can change the position, rotation, scale and opacity. this will in turn convert all the nodes into triggers that GD can read.

**Comment by AlFasGD** [comment]
Something like an animator?

**Comment by Altenhh** [comment]
somewhat, watch [this](https://youtu.be/88n15kj2-WA?t=2238) part of the video to figure out what im trying to say

**Comment by AlFasGD** [comment]
Basically keyframes, which are already planned
