### ISSUE TITLE
Published version

### ISSUE THREAD

**Issue by DepthsGD** [gd-edit/GDE#153]
@Altenhh  I've made a published version of the software.
Please can I upload it to the repository?

**Comment by AlFasGD** [comment]
We are not publishing every single change we make, rather we prefer publishing completed milestones (that haven't been met in a long while). We will publish a new version as soon as we get to that point, until then people will have to stick with the previous publish or the unstable `master`.

**Comment by Altenhh** [comment]
currently I am working on a complete overhaul for the project which will have more of a Blender feel to the project aswell as having the same ui to Blender.  I also already have a build script for the project that will automatically build and release a new version. if you want I can create a new repository so that you can also automatically publish new versions of the software on your own repository.

**Comment by DepthsGD** [comment]
How about you add a folder to the new repository containing the contents of the old one?

On 16 February 2020, at 16:28, Alten <notifications@github.com> wrote:

currently I am working on a complete overhaul for the project which will have more of a Blender feel to the project aswell as having the same ui to Blender. I also already have a build script for the project that will automatically build and release a new version. if you want I can create a new repository so that you can also automatically publish new versions of the software on your own repository.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/gd-edit/GDE/issues/153?email_source=notifications">https://github.com/gd-edit/GDE/issues/153?email_source=notifications</a>\u0026email_token=ANW4YCPK5BOD3CYAE5ILENTRDFSRBA5CNFSM4KWA65YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4LRJA#issuecomment-586725540", "url": "<a href="https://github.com/gd-edit/GDE/issues/153?email_source=notifications">https://github.com/gd-edit/GDE/issues/153?email_source=notifications</a>\u0026email_token=ANW4YCPK5BOD3CYAE5ILENTRDFSRBA5CNFSM4KWA65YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4LRJA#issuecomment-586725540", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by Altenhh** [comment]
I'm not too sure on what your intention for that is? why would you keep a copy of the old content for the new repo? like I've said earlier it's ready to be published to git and I'll have a tutorial on how to set it up premade already.

**Comment by DepthsGD** [comment]
For archiving reasons, and so people can see what GD-Edit used to be like.

On 16 February 2020, at 16:28, Alten <notifications@github.com> wrote:

currently I am working on a complete overhaul for the project which will have more of a Blender feel to the project aswell as having the same ui to Blender. I also already have a build script for the project that will automatically build and release a new version. if you want I can create a new repository so that you can also automatically publish new versions of the software on your own repository.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/gd-edit/GDE/issues/153?email_source=notifications">https://github.com/gd-edit/GDE/issues/153?email_source=notifications</a>\u0026email_token=ANW4YCPK5BOD3CYAE5ILENTRDFSRBA5CNFSM4KWA65YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4LRJA#issuecomment-586725540", "url": "<a href="https://github.com/gd-edit/GDE/issues/153?email_source=notifications">https://github.com/gd-edit/GDE/issues/153?email_source=notifications</a>\u0026email_token=ANW4YCPK5BOD3CYAE5ILENTRDFSRBA5CNFSM4KWA65YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4LRJA#issuecomment-586725540", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by DepthsGD** [comment]
P.S. Can I help by testing the software?

On 18 February 2020, at 07:06, Alten <notifications@github.com> wrote:

I'm not too sure on what your intention for that is? why would you keep a copy of the old content for the new repo? like I've said earlier it's ready to be published to git and I'll have a tutorial on how to set it up premade already.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/gd-edit/GDE/issues/153?email_source=notifications">https://github.com/gd-edit/GDE/issues/153?email_source=notifications</a>\u0026email_token=ANW4YCJNEWPB7E2IQZAFLBLRDOCIHA5CNFSM4KWA65YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMA263A#issuecomment-587313004", "url": "<a href="https://github.com/gd-edit/GDE/issues/153?email_source=notifications">https://github.com/gd-edit/GDE/issues/153?email_source=notifications</a>\u0026email_token=ANW4YCJNEWPB7E2IQZAFLBLRDOCIHA5CNFSM4KWA65YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMA263A#issuecomment-587313004", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by ok-what** [comment]
> For archiving reasons, and so people can see what GD-Edit used to be like.

You can roll back to an earlier commit that doesn't have that redesign or use an old release.
