### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by Tevo45** [gd-edit/GDE#77]
Implement support for platforms such as macOS/Darwin, Windows and Linux-based operating systems. Most work is already done under the hood by .NET Core and osu!framework, so this should just boil down to maintaining coding practices that guarantee that the code will stay multiplatform.

**Comment by AltenGD** [comment]
ill leave this to @AlFasGD to do since this is mostly a backend issue. (see [GDE/Database](https://github.com/gd-edit/GDE/blob/master/GDEdit/GDEdit/Application/Database.cs#L49))

**Comment by AlFasGD** [comment]
Personally I don't know much about other platforms so this'll be a community effort for the most part.

**Comment by AlFasGD** [comment]
Not explicitly relevant and too vague to be held an issue; also should be handled [here](https://github.com/gd-edit/GDAPI).
