### ISSUE TITLE
Master approved suggestions

### ISSUE THREAD

**Issue by AltenGD** [gd-edit/GDE#80]
# If you want to get your suggestion here, please open an issue with the details of your suggestions

## General

- [ ] Basic editor functionality
- [ ] Custom files for the editor. Allows you to have features specific to this tool saved.
- [ ] Autosave
- [ ] Unlimited custom objects
- [ ] When you go over the object limit, the program warns you but doesn't limit you.
- [ ] Add-ons and custom scripts.
- [ ] In game timer / time in editor
- [ ] Next free layer button

## Functions

- [ ] some sort of 'for loop'-like thing to place/edit/delete a lot of the same action over and over with different groups (probably even within triggers), colors, etc.
- [ ] Automatic block variation
- [ ] Looping trigger module.
- [ ] Option for randomised block rotation and scale for placing objects.
- [ ] Scattering objects or object groups randomly over a specified area
- [ ] Speed control (.50x, .25x, etc)
- [ ] Replace object(s) with other object(s)
- [ ] Linking object data like id's and colours to other objects.
- [ ] Proportional editing. Has many falloff types like:
- [ ] Linear, sharp, constant (to move multiple objects at once), sphere and random (https://bit.ly/2z2UQLe)
- [ ] Pivot point dropdown (https://streamable.com/22ouq https://bit.ly/2JhnrRG)
- [ ] Smart Replace (https://bit.ly/2JkafeS)

## User Interface

- [ ] RGBA/HEX color selector with the ability to type in the specific numbers.
- [ ] Color trigger easing preset.
- [ ] Newgrounds song browser.
- [ ] Better trigger organization
- [ ] Ability to open a trigger menu as a window from the properties panel
- [ ] Ability to add notes inside the level
- [ ] Scene view
- [ ] Camera indicator when playtesting. Moves like the in-game camera. Different options for monitor resolutions and styles: corner indicators, white border, hide outside (Covers everything but what the player would be able to see)

## Settings

- [ ] Ability to customise keybindings.
- [ ] Dark mode
- [ ] Checkbox for automatic updates.
- [ ] Selection
- [ ] Filters for editing, deleting, selecting and visibility. (by group, object type etc.)
- [ ] Ability to select a bunch of triggers and make it select the target group IDs.
- [ ] Selecting an object and choosing select linked. This pops up a menu that allows you to select everything of the same type (color, group, rotation, editor layer, actual layer, obj type)
- [ ] Randomised selection over an area

## Triggers

- [ ] When you have multiple triggers selected you can edit their common properties.
- [ ] Interaction
- [ ] Scroll -> vertical Scroll
- [ ] shift+scroll -> horizontal scroll
- [ ] ctrl+scroll -> zoom
- [ ] middle click down -> moving the scene ?
- [ ] When you perform an action such as scale(s) or rotate(r) with their keyboard shortcuts, you can type the rotation or scale value in.
- [ ] Right click -> Delete

## Scripts

- [ ] Automatic circle generator

**Comment by AlFasGD** [comment]
Move this to the wiki?

**Comment by AltenGD** [comment]
actually yeah lmfao
