### ISSUE TITLE
Master feature list

### ISSUE THREAD

**Issue by AltenGD** [gd-edit/GDE#81]
This contains the list of features of the project; useful for both developers and users

## General

- [ ] Autosave
- [ ] No fucking limits anywhere; literally (only warnings)
- [ ] Editor Timer
- [ ] Next Free buttons everywhere
- [ ] Hitbox Viewing
- [ ] Speed Control
- [ ] Custom Object Editor
- [ ] Color Channel Editor
- [ ] Initial Object Values Editor
- [ ] Extra Level Editor Functions
 - - [ ] Create Base/Edges/Outlines/Decoration Outlines/Cornerpieces
 - - [ ] Reset Unused Color Channels/Groups
 - - [ ] Uncheck Selected Portals
 - - [ ] Snap To Grid/Guidelines
- [ ] Newgrounds Song Browser
- [x] Discord Rich Presence

## Multi-Level

- [ ] Guideline Editor
- [x] Level Overview
- [ ] Level Version Converter

Selection

- [ ] Quick Selection
 - - [ ] Select triggers affecting currently selected object(s)
 - - [ ] Select objects being affected by currently selected trigger(s)
 - - [ ] Select triggers that target the chosen IDs
 - - [ ] Select objects with the same parameters
- [ ] Selection Filters
- [ ] Multiple Object Editing
- [ ] Presets
 - - [ ] Auto Copy-Paste
 - - [ ] Auto Adjust Group IDs
 - - [ ] Guideline Creation

## Macros

- [ ] Copy-Paste Adjustment
 - - [ ] Object Type Filtering
- [ ]  Design Assistant
- [ ]  Group ID Migration
- [ ]  Plugins
- [ ]  Random Object Placement
- [ ]  Trigger Effect Easings

## Advanced

- [ ]  Proportional Editing (https://bit.ly/2z2UQLe)
- [ ]  Pivot Point (https://streamable.com/22ouq / https://bit.ly/2JhnrRG)
- [ ]  RGBA/HSV Hex Color Editor
- [ ]  Custom Object Selection Toolbars (single-/multi-selection)

**Comment by AlFasGD** [comment]
Move this on README.md or somewhere else

**Comment by AltenGD** [comment]
well leave this here, it'll clutter up more space if we do that. + we can also have comments and other stuffs

**Comment by AlFasGD** [comment]
Actually I have a great idea, migrate this to a .md where README.md is (in the main directory of the repo) and name it something like FeatureList.md, containing all this. Link it to README.md, and so do for the other cluttery stuff that have been added there. Should be much more maintainable and organized; besides keeping track of features and stuff through issues doesn't seem good to me.
