### ISSUE TITLE
New site for GDE

### ISSUE THREAD

**Issue by Altenhh** [gd-edit/GDE#86]
I've had this kind of idea for a while now but im always not sure if i should try it which is why im going to be making a suggestion out of it instead

This will allow users to post block designs, scripts, and other stuffs. it will be really handy for our add-ons over at the GDE app. We can also do blog posts about recent updates or just important things overall.

ill drop some website design under the thread sooner or later.

**Comment by AlFasGD** [comment]
This issue and other web-related issues should be handled [here](https://github.com/gd-edit/GDE-Web).
