### ISSUE TITLE
dude stop using stuff from the osu! framework

### ISSUE THREAD

**Issue by prometheus1337** [gd-edit/GDE#89]
ppy is probably mad

**Comment by AltenGD** [comment]
osu!framework provides us ease of functionality and performance. there is a reason why it's public, we are free to chose whichever game framework we please.

**Comment by AlFasGD** [comment]
https://clips.twitch.tv/SuspiciousUninterestedSlothPeanutButterJellyTime peppy is really mad we are using his framework @prometheus1337

**Comment by Altenhh** [comment]
:wheeze:

**Comment by prometheus1337** [comment]
and please dont bump this
